"""empty message

Revision ID: 823df1408740
Revises: f0543279393d
Create Date: 2020-05-23 21:05:04.499951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823df1408740'
down_revision = 'f0543279393d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=70), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('industry_group', sa.String(length=120), nullable=True),
    sa.Column('sub_industry', sa.String(length=120), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('best_for', sa.String(length=120), nullable=True),
    sa.Column('contact_details', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_best_for'), 'solutions', ['best_for'], unique=False)
    op.create_index(op.f('ix_solutions_contact_details'), 'solutions', ['contact_details'], unique=False)
    op.create_index(op.f('ix_solutions_details'), 'solutions', ['details'], unique=False)
    op.create_index(op.f('ix_solutions_industry'), 'solutions', ['industry'], unique=False)
    op.create_index(op.f('ix_solutions_industry_group'), 'solutions', ['industry_group'], unique=False)
    op.create_index(op.f('ix_solutions_name'), 'solutions', ['name'], unique=False)
    op.create_index(op.f('ix_solutions_sector'), 'solutions', ['sector'], unique=False)
    op.create_index(op.f('ix_solutions_sub_industry'), 'solutions', ['sub_industry'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solutions_sub_industry'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_sector'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_name'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_industry_group'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_industry'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_details'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_contact_details'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_best_for'), table_name='solutions')
    op.drop_table('solutions')
    # ### end Alembic commands ###
